version: '3'
services:
  backend:
    build : .
    deploy:
      replicas: 3
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/app`)"
      - "traefik.http.middlewares.backend.stripPrefix.prefixes=/app"
      - "traefik.http.routers.backend.middlewares=backend@docker"

  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
        -   ./data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_PASSWORD: admin
